### ISSUE TITLE
More context in README and Tool description

### ISSUE THREAD

**Issue by skfd** [code-nybbler/CodeTableGenerator#1]
Could you please give an example of what this tool should be used for, some more description, please!

**Comment by code-nybbler** [comment]
@skfd This tool is specifically designed to be used within the context of XrmToolBox, a suite of opensource plugins targeting the Microsoft Dynamics 365 platform. This tool allows users to quickly create code tables within their chosen D365 environment using a more streamlined approach, rather than using the more tedious solution editor of D365. For most clients, a "code table" will only consist of the primary column, a column to hold the short "code" value, and an optional description column.

This tool will most likely not be useful to anyone outside the context of XrmToolBox/Dynamics plugin-writing.
